spring.application.name=muzayede
#
## H2 veritabanni icin ayarlar
#spring.datasource.url=jdbc:h2:mem:muzayedeinram
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=umut
#spring.datasource.password=
#
## Hibernate Ayarlari
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

## H2 Konsolunu tarayici uzerinden erisim icin
#spring.h2.console.enabled=true

# PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/muzayede_db
spring.datasource.username=postgres
spring.datasource.password=123456789

# JPA / Hibernate Ayarları
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true